spring.application.name=SpringBoot_third_project
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/Spring_Boot1
spring.datasource.username=postgres
spring.datasource.password=(nikash)

spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=nikash1231akdjslkajdaksdjflaksdjflaksdflaksdjfakdjfb1231ksdjajsdhflakdjshfuehfadsfasdf
jwt.expiration=3600000
