spring.application.name=SpringBootProject1
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_database1
spring.datasource.username=postgres
spring.datasource.password=Kamala123@

spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


jwt.secret=ayushxyzshrestha04110517abcdefffgaslksjgdfgoiasnddskfjn2335sdfsklhukaiuCJ
jwt.expiration=3600000