spring.application.name=SpringBootProject1
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_database1
spring.datasource.username=postgres
spring.datasource.password=Kamala123@

spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


jwt.secret=ayushxyzshrestha04110517abcdefffgaslksjgdfgoiasnddskfjn2335sdfsklhukaiuCJ
jwt.expiration=3600000


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ayush.shrestha517@gmail.com
spring.mail.password=jhnfjyorlqztlfge

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true